SWC_DIAG_DEF(ParserReservedAsIdentifier, Note, "a {tok-fam} cannot be used as an identifier")
SWC_DIAG_DEF(ParserCorresponding, Note, "this is the related {expect-tok-fam}")

SWC_DIAG_DEF(ParserHelpEmptyArrayDim, Help, "expected one of '[*]' (pointer), '[..]' (slice), '[?]' (inferred array), or a numeric dimension")

SWC_DIAG_DEF(BecauseEnumValues, Note, "to separate enum values")
SWC_DIAG_DEF(BecauseStartEnumBody, Note, "to start enum body")

