SWC_DIAG_DEF(ParserReservedAsIdentifier, Note, "a {tok-fam} cannot be used as an identifier")

SWC_DIAG_DEF(BecauseEnumValues, Note, "to separate enum values")
SWC_DIAG_DEF(BecauseStartEnumBody, Note, "to start enum body")
SWC_DIAG_DEF(BecauseIncompleteArrayType, Note, "in '[?]' type expression")
SWC_DIAG_DEF(BecausePtrBlockType, Note, "in '[*]' type expression")
SWC_DIAG_DEF(BecauseSliceType, Note, "in '[..]' type expression")

