SWC_NODE_ID_DEF(Invalid)
SWC_NODE_ID_DEF(Identifier)

SWC_NODE_ID_DEF(File)
SWC_NODE_ID_DEF(TopLevelBlock)

SWC_NODE_ID_DEF(EnumDecl)
SWC_NODE_ID_DEF(EnumBlock)
SWC_NODE_ID_DEF(EnumValue)
SWC_NODE_ID_DEF(EnumUsingValue)
SWC_NODE_ID_DEF(EnumImpl)

SWC_NODE_ID_DEF(QualifiedType)
SWC_NODE_ID_DEF(LRefType)
SWC_NODE_ID_DEF(RRefType)
SWC_NODE_ID_DEF(PointerType)
SWC_NODE_ID_DEF(BlockPointerType)
SWC_NODE_ID_DEF(NamedType)
SWC_NODE_ID_DEF(BuiltinType)
SWC_NODE_ID_DEF(SliceType)
SWC_NODE_ID_DEF(IncompleteArrayType)
SWC_NODE_ID_DEF(ArrayType)

SWC_NODE_ID_DEF(CompilerAssert)

