#!/usr/bin/env python3
"""Audit one static HTML page generated by `swc doc` in API mode."""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from collections import Counter
from pathlib import Path
from urllib.parse import unquote


API_ITEM_RE = re.compile(
    r'<div class="api-item[^"]*">.*?'
    r'<span id="(?P<anchor>[^"]+)"[^>]*>.*?'
    r'<span class="api-item-title-kind">(?P<kind>[^<]+)</span>\s*'
    r'<span class="api-item-title-strong">(?P<name>.*?)</span>.*?'
    r"</div>\s*(?P<body>.*?)"
    r'(?=<div class="api-item[^"]*">|</article>|</main>)',
    re.DOTALL,
)
MEMBER_TABLE_RE = re.compile(
    r"<h3[^>]*>(?P<title>Fields|Cases)</h3>\s*"
    r'<table class="[^"]*\btable-enumeration\b[^"]*">(?P<body>.*?)</table>',
    re.DOTALL,
)
ROW_RE = re.compile(r"<tr>(?P<body>.*?)</tr>", re.DOTALL)
CELL_RE = re.compile(r"<td(?:\s+[^>]*)?>(?P<body>.*?)</td>", re.DOTALL)
SUMMARY_TABLE_RE = re.compile(
    r'<table class="[^"]*\bapi-summary\b[^"]*">(?P<body>.*?)</table>',
    re.DOTALL,
)
TAG_RE = re.compile(r"<[^>]+>")
ID_RE = re.compile(r'\bid="([^"]+)"')
LOCAL_HREF_RE = re.compile(r'\bhref="#([^"]+)"')
PAGE_HREF_RE = re.compile(r'\bhref="([^"#?]+\.html)#([^"]+)"')
RESERVED_IDENTIFIER_RE = re.compile(r"(?<![A-Za-z0-9_])__[A-Za-z0-9_]+")
SCRIPT_RE = re.compile(r"<\s*script\b", re.IGNORECASE)
PHP_RE = re.compile(r"<\?php", re.IGNORECASE)
UNRESOLVED_REFERENCE_RE = re.compile(r"\[\[([^\]]+)\]\]")
CODE_BLOCK_RE = re.compile(r'<div class="code-block">.*?</div>', re.DOTALL)
INLINE_CODE_RE = re.compile(r'<span class="code-inline">.*?</span>', re.DOTALL)
NESTED_SYMBOL_SECTION_RE = re.compile(r'class="api-method-details"')
EXAMPLE_RE = re.compile(
    r'<h[1-6][^>]*>\s*Examples?\s*</h[1-6]>|class="blockquote-example"',
    re.IGNORECASE,
)
SOURCE_LOCATION_RE = re.compile(
    r"/blob/[^/]+/(?P<path>[^#]+)#L(?P<line>[0-9]+)$"
)
SUMMARY_MAX_LENGTH = 140


def plain_text(fragment: str) -> str:
    text = TAG_RE.sub(" ", fragment)
    return " ".join(html.unescape(text).split())


def first_signature_offset(body: str) -> int:
    offset = body.find('<div class="code-block"')
    return len(body) if offset == -1 else offset


def has_unseparated_long_description(
    source_root: Path, source_link: str
) -> bool:
    match = SOURCE_LOCATION_RE.search(source_link)
    if not match:
        return False

    source_path = source_root / Path(unquote(match.group("path")))
    if not source_path.is_file():
        return False

    lines = source_path.read_text(encoding="utf-8").splitlines()
    index = int(match.group("line")) - 2
    while index >= 0 and lines[index].strip().startswith("#["):
        index -= 1

    comments: list[str] = []
    while index >= 0 and lines[index].lstrip().startswith("//"):
        comments.append(lines[index].lstrip()[2:].strip())
        index -= 1
    comments.reverse()

    non_empty = sum(bool(line) for line in comments)
    return non_empty > 1 and not any(not line for line in comments[1:])


def audit(path: Path, source_root: Path | None = None) -> dict[str, object]:
    source = path.read_text(encoding="utf-8")
    ids = ID_RE.findall(source)
    id_counts = Counter(ids)
    duplicate_ids = sorted(name for name, count in id_counts.items() if count > 1)
    broken_anchors = sorted(set(LOCAL_HREF_RE.findall(source)) - set(ids))
    broken_page_anchors: list[str] = []
    page_ids: dict[Path, set[str]] = {}
    for page_name, anchor in sorted(set(PAGE_HREF_RE.findall(source))):
        page_path = (path.parent / html.unescape(page_name)).resolve()
        if not page_path.is_file():
            broken_page_anchors.append(f"{page_name}#{anchor} (missing page)")
            continue
        if page_path not in page_ids:
            page_ids[page_path] = set(
                ID_RE.findall(page_path.read_text(encoding="utf-8"))
            )
        if html.unescape(anchor) not in page_ids[page_path]:
            broken_page_anchors.append(f"{page_name}#{anchor}")
    synthetic_names = sorted(set(RESERVED_IDENTIFIER_RE.findall(plain_text(source))))
    prose_source = CODE_BLOCK_RE.sub("", source)
    prose_source = INLINE_CODE_RE.sub("", prose_source)
    unresolved_references = sorted(
        set(UNRESOLVED_REFERENCE_RE.findall(plain_text(prose_source)))
    )
    long_summaries: list[str] = []
    seen_summaries: set[tuple[str, str]] = set()
    for table_match in SUMMARY_TABLE_RE.finditer(source):
        for row_match in ROW_RE.finditer(table_match.group("body")):
            cells = CELL_RE.findall(row_match.group("body"))
            if len(cells) < 2:
                continue
            name = plain_text(cells[0])
            description = plain_text(cells[-1])
            key = (name, description)
            if (
                description
                and len(description) > SUMMARY_MAX_LENGTH
                and key not in seen_summaries
            ):
                seen_summaries.add(key)
                long_summaries.append(
                    f"{name} ({len(description)} characters)"
                )

    items: list[dict[str, object]] = []
    undocumented_items: list[str] = []
    undocumented_item_details: list[dict[str, str]] = []
    undocumented_members: list[str] = []
    undocumented_values: list[str] = []
    example_items: list[str] = []
    kinds: Counter[str] = Counter()
    total_members = 0
    total_values = 0
    unseparated_descriptions: list[str] = []

    for match in API_ITEM_RE.finditer(source):
        name = plain_text(match.group("name"))
        kind = plain_text(match.group("kind"))
        body = match.group("body")
        summary_fragment = body[: first_signature_offset(body)]
        has_description = bool(plain_text(summary_fragment))
        has_example = bool(EXAMPLE_RE.search(body))
        header = match.group(0)[: match.start("body") - match.start()]
        source_match = re.search(
            r'class="api-item-title-src-ref".*?\bhref="([^"]+)"',
            header,
            re.DOTALL,
        )
        source_link = html.unescape(source_match.group(1)) if source_match else ""
        if (
            source_root is not None
            and source_link
            and has_unseparated_long_description(source_root, source_link)
        ):
            unseparated_descriptions.append(name)

        kinds[kind] += 1
        if not has_description:
            undocumented_items.append(name)
            undocumented_item_details.append({"name": name, "source": source_link})
        if has_example:
            example_items.append(name)

        missing_members: list[str] = []
        for table_match in MEMBER_TABLE_RE.finditer(body):
            table_title = table_match.group("title")
            for row_match in ROW_RE.finditer(table_match.group("body")):
                cells = CELL_RE.findall(row_match.group("body"))
                if len(cells) < 2:
                    continue
                member_name = plain_text(cells[0])
                description = plain_text(cells[-1])
                qualified_name = f"{name}.{member_name}"
                if table_title == "Cases":
                    total_values += 1
                else:
                    total_members += 1
                if not description and table_title == "Cases":
                    undocumented_values.append(qualified_name)
                elif not description:
                    missing_members.append(qualified_name)
                    undocumented_members.append(qualified_name)

        items.append(
            {
                "name": name,
                "kind": kind,
                "anchor": match.group("anchor"),
                "source": source_link,
                "documented": has_description,
                "has_example": has_example,
                "undocumented_members": missing_members,
            }
        )

    css_links = re.findall(
        r'<link\b[^>]*\brel="stylesheet"[^>]*\bhref="([^"]+)"',
        source,
        re.IGNORECASE,
    )
    missing_css: list[str] = []
    for link in css_links:
        if "://" in link or link.startswith("/"):
            continue
        css_path = (path.parent / html.unescape(link)).resolve()
        if not css_path.is_file():
            missing_css.append(link)

    return {
        "path": str(path),
        "items": len(items),
        "kinds": dict(sorted(kinds.items())),
        "documented_items": len(items) - len(undocumented_items),
        "undocumented_items": undocumented_items,
        "undocumented_item_details": undocumented_item_details,
        "members": total_members,
        "documented_members": total_members - len(undocumented_members),
        "enum_values": total_values,
        "documented_values": total_values - len(undocumented_values),
        "undocumented_members": undocumented_members,
        "undocumented_values": undocumented_values,
        "items_with_examples": len(example_items),
        "example_items": example_items,
        "synthetic_names": synthetic_names,
        "unresolved_references": unresolved_references,
        "long_summaries": long_summaries,
        "unseparated_descriptions": sorted(set(unseparated_descriptions)),
        "nested_symbol_sections": len(NESTED_SYMBOL_SECTION_RE.findall(source)),
        "duplicate_ids": duplicate_ids,
        "broken_anchors": broken_anchors,
        "broken_page_anchors": broken_page_anchors,
        "scripts": len(SCRIPT_RE.findall(source)),
        "php_blocks": len(PHP_RE.findall(source)),
        "stylesheets": css_links,
        "missing_stylesheets": missing_css,
    }


def print_list(title: str, values: list[str], limit: int) -> None:
    print(f"{title}: {len(values)}")
    for value in values[:limit]:
        print(f"  - {value}")
    if len(values) > limit:
        print(f"  ... {len(values) - limit} more")


def print_report(report: dict[str, object], limit: int) -> None:
    kinds = ", ".join(f"{name}={count}" for name, count in report["kinds"].items())
    print(f"API documentation audit: {report['path']}")
    print(f"Items: {report['items']} ({kinds})")
    print(f"Documented items: {report['documented_items']}/{report['items']}")
    print(f"Documented members: {report['documented_members']}/{report['members']}")
    print(f"Documented enum values: {report['documented_values']}/{report['enum_values']}")
    print(f"Items with examples: {report['items_with_examples']}/{report['items']}")
    print(f"Undocumented items: {len(report['undocumented_item_details'])}")
    for detail in report["undocumented_item_details"][:limit]:
        suffix = f" — {detail['source']}" if detail["source"] else ""
        print(f"  - {detail['name']}{suffix}")
    if len(report["undocumented_item_details"]) > limit:
        print(f"  ... {len(report['undocumented_item_details']) - limit} more")
    print_list("Undocumented members", report["undocumented_members"], limit)
    print_list("Enum values without comments", report["undocumented_values"], limit)
    print_list("Synthetic identifiers", report["synthetic_names"], limit)
    print_list("Unresolved symbol references", report["unresolved_references"], limit)
    print_list(
        f"Summaries longer than {SUMMARY_MAX_LENGTH} characters",
        report["long_summaries"],
        limit,
    )
    print_list(
        "Long descriptions without a blank comment line",
        report["unseparated_descriptions"],
        limit,
    )
    print(f"Nested canonical symbol sections: {report['nested_symbol_sections']}")
    print_list("Duplicate HTML ids", report["duplicate_ids"], limit)
    print_list("Broken local anchors", report["broken_anchors"], limit)
    print_list("Broken cross-page anchors", report["broken_page_anchors"], limit)
    print_list("Missing stylesheets", report["missing_stylesheets"], limit)
    print(f"Forbidden elements: scripts={report['scripts']}, php={report['php_blocks']}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Audit a static API page generated by `swc doc`."
    )
    parser.add_argument("html", type=Path, help="Generated API HTML file.")
    parser.add_argument(
        "--require-complete",
        action="store_true",
        help="Also fail when an API item or member has no documentation.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print the complete machine-readable report.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=30,
        help="Maximum entries shown per issue category in text mode.",
    )
    parser.add_argument(
        "--source-root",
        type=Path,
        help="Repository root used to audit source-comment summary separators.",
    )
    args = parser.parse_args()

    if not args.html.is_file():
        parser.error(f"file not found: {args.html}")
    if args.source_root is not None and not args.source_root.is_dir():
        parser.error(f"source root not found: {args.source_root}")

    source_root = args.source_root.resolve() if args.source_root else None
    report = audit(args.html.resolve(), source_root)
    if args.json:
        print(json.dumps(report, indent=2, ensure_ascii=False))
    else:
        print_report(report, max(0, args.limit))

    hard_failures = (
        report["synthetic_names"]
        or report["unresolved_references"]
        or report["long_summaries"]
        or report["unseparated_descriptions"]
        or report["nested_symbol_sections"]
        or report["duplicate_ids"]
        or report["broken_anchors"]
        or report["broken_page_anchors"]
        or report["missing_stylesheets"]
        or report["scripts"]
        or report["php_blocks"]
    )
    incomplete = report["undocumented_items"] or report["undocumented_members"]
    return 1 if hard_failures or (args.require_complete and incomplete) else 0


if __name__ == "__main__":
    sys.exit(main())
