#include "pch.h"
#include "Doc/DocInternal.h"
#include "Compiler/Lexer/SourceView.h"
#include "Compiler/ModuleApi/ModuleApi.Export.h"
#include "Compiler/Parser/Ast/Ast.h"
#include "Compiler/Parser/Ast/AstNodes.h"
#include "Compiler/Sema/Constant/ConstantManager.h"
#include "Compiler/Sema/Core/AttributeList.h"
#include "Compiler/Sema/Symbol/Symbol.Impl.h"
#include "Compiler/Sema/Symbol/SymbolMap.h"
#include "Compiler/Sema/Symbol/Symbols.h"
#include "Compiler/Sema/Type/TypeInfo.h"
#include "Compiler/SourceFile.h"
#include "Main/Command/CommandLine.h"
#include "Main/Command/CommandLineParser.h"
#include "Main/CompilerInstance.h"
#include "Main/FileSystem.h"
#include "Main/TaskContext.h"
#include "Main/Version.h"
#include "Support/Report/Diagnostic.h"
#include "Support/Report/SyntaxColor.h"

SWC_BEGIN_NAMESPACE();

namespace DocInternal
{

    Utf8 documentationStyles()
    {
        Utf8 result = R"(/*
 * Static stylesheet generated by swc doc.
 * The documentation intentionally needs no script or server-side runtime.
 */

:root {
    color-scheme: light;
    --swag-black: #050505;
    --swag-yellow: #f7f900;
    --swag-link: #1677c8;
    --swag-line: #d7d7d7;
    --swag-soft: #f3f3f3;
    --swag-header-height: 74px;
}

* {
    box-sizing: border-box;
}

html {
    scroll-behavior: smooth;
}

body {
    margin: 0;
    color: #222;
    background: #fff;
    font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
    line-height: 1.45;
}

.site-header {
    position: sticky;
    z-index: 10;
    top: 0;
    min-height: var(--swag-header-height);
    color: #fff;
    background: var(--swag-black);
    border-bottom: 3px solid var(--swag-yellow);
}

.site-nav {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 28px;
    width: min(1200px, calc(100% - 32px));
    min-height: var(--swag-header-height);
    margin: 0 auto;
}

.site-brand {
    color: var(--swag-yellow);
    font-size: 1.45rem;
    font-weight: 800;
    letter-spacing: .14em;
    text-decoration: none;
}

.site-links {
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-end;
    gap: 8px 22px;
}

.site-links a {
    color: #fff;
    text-decoration: none;
}

.site-links a:hover,
.site-links a:focus-visible {
    color: var(--swag-yellow);
}

.container {
    display: grid;
    grid-template-columns: minmax(230px, 330px) minmax(0, 1fr);
    gap: 34px;
    width: min(1500px, calc(100% - 32px));
    margin: 0 auto;
}

.container.single-page {
    display: block;
}

.left {
    position: sticky;
    top: var(--swag-header-height);
    height: calc(100vh - var(--swag-header-height));
    overflow-y: auto;
    border-right: 1px solid var(--swag-line);
}

.left-page {
    padding: 24px 24px 40px 4px;
}

.left h2 {
    margin-top: 0;
}

.left h3 {
    margin: 28px 0 8px;
    padding: 7px 9px;
    color: #fff;
    background: var(--swag-black);
}

.left h4 {
    margin: 18px 0 6px;
}

.left ul {
    margin: 0;
    padding-left: 14px;
    list-style: none;
}

.left li {
    margin: 3px 0;
}

.right {
    min-width: 0;
}

.right-page {
    width: min(100%, 1024px);
    margin: 0 auto;
    padding: 30px 10px 48px;
}

.single-page .right-page {
    padding-top: 34px;
}

.right h1 {
    margin: 32px 0 22px;
    font-size: clamp(2rem, 5vw, 3rem);
    line-height: 1.1;
}

.right h2 {
    margin-top: 42px;
}

.right hr {
    margin: 48px 0;
    border: 0;
    border-top: 1px solid var(--swag-line);
}

.module-overview {
    padding-bottom: 30px;
    border-bottom: 1px solid var(--swag-line);
    font-size: 1.05rem;
}

.module-overview > p:first-of-type {
    max-width: 76ch;
    color: #444;
    font-size: 1.12rem;
}

.api-guide {
    padding: 12px 0 30px;
    border-bottom: 1px solid var(--swag-line);
}

.api-overview {
    padding-top: 10px;
}

.api-symbol {
    margin-top: 54px;
}

[id] {
    scroll-margin-top: calc(var(--swag-header-height) + 16px);
}

.container a {
    color: var(--swag-link);
}

.container a:hover {
    text-decoration: underline;
}

.container img {
    max-width: 100%;
    height: auto;
}

.no-decoration,
.round-button a,
.left a,
.table-enumeration a {
    text-decoration: none;
}

.round-button {
    display: inline-block;
    margin: 10px 5px;
    padding: 10px 14px;
    text-align: center;
    border: 1px solid #777;
    border-radius: 5px;
}

.strikethrough-text {
    text-decoration: line-through;
}

.swag-watermark {
    margin-top: 40px;
    color: #666;
    font-size: 80%;
    text-align: right;
}

.swag-watermark a {
    color: inherit;
    text-decoration: none;
}

.blockquote {
    margin: 20px;
    padding: 12px 14px;
    border: 1px solid;
    border-radius: 5px;
}

.blockquote-default {
    background: #ffffe0;
    border-color: orange;
    border-left-width: 6px;
}

.blockquote-note {
    background: #cdeefd;
    border-color: #adcedd;
}

.blockquote-tip {
    background: #dcefdc;
    border-color: #bccfbc;
}

.blockquote-warning {
    background: #ffddd3;
    border-color: #dfbdb3;
}

.blockquote-attention {
    background: #fddad8;
    border-color: #ddbab8;
}

.blockquote-example {
    border: 2px solid var(--swag-line);
}

.blockquote-title-block {
    margin-bottom: 10px;
}

.blockquote-title {
    font-weight: 700;
}

.description-list-title {
    font-weight: 700;
    font-style: italic;
}

.description-list-block {
    margin-left: 30px;
}

.container table {
    max-width: 100%;
    margin: 20px 0;
    border: 1px solid var(--swag-line);
    border-collapse: collapse;
    font-size: 90%;
}

.container td,
.container th {
    min-width: 100px;
    padding: 7px;
    border: 1px solid var(--swag-line);
}

.container th {
    background: #eee;
}

.table-markdown {
    width: 100%;
}

table.api-item {
    width: 100%;
    margin: 70px 0 0;
    color: #fff;
    background: var(--swag-black);
    border-collapse: separate;
    font-size: 110%;
}

.api-item td {
    border: 0;
}

.api-item td:first-child {
    width: 66%;
}

.api-item-title-src-ref {
    text-align: right;
}

.api-item-title-src-ref a {
    color: inherit;
}

.api-item-title-kind {
    font-size: 80%;
    font-weight: 400;
}

.api-item-title-strong {
    font-weight: 700;
}

.table-enumeration {
    width: 100%;
}

.api-summary {
    width: 100%;
}

.api-summary td:first-child {
    white-space: nowrap;
}

.api-summary p {
    margin: 0;
}

.table-enumeration td:first-child {
    white-space: nowrap;
    background: #f8f8f8;
}

.table-enumeration td:last-child {
    width: 100%;
}

.table-enumeration td.code-type {
    background: #eee;
}

.code-inline {
    display: inline-block;
    padding: 0 7px;
    background: #eee;
    border: 1px dotted #ccc;
    border-radius: 5px;
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
}

.code-block {
    margin: 20px 0;
    padding: 12px;
    overflow-x: auto;
    background: var(--swag-soft);
    border: 1px solid var(--swag-line);
    border-radius: 5px;
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    white-space: pre;
}

.code-block a {
    color: inherit;
}

.SCmt { color: #6a9955; }
.SCmp, .SAtr { color: #777; }
.SFct { color: #c54f00; }
.SCst { color: #168f7d; }
.SItr { color: #8a7600; }
.STpe { color: #a66c00; }
.SKwd { color: #286fa8; }
.SLgc { color: #8e4d99; }
.SNum { color: #4d7a45; }
.SStr { color: #a64f38; }
.SInv { color: #d22; }
.SBcR { color: #817c31; }
.SCde { color: var(--swag-code-default, #222); }

@media (max-width: 780px) {
    :root {
        --swag-header-height: 112px;
    }

    .site-nav {
        align-items: flex-start;
        padding: 14px 0;
    }

    .site-links {
        gap: 6px 14px;
    }

    .container {
        display: block;
    }

    .left {
        position: static;
        width: 100%;
        height: auto;
        border-right: 0;
        border-bottom: 1px solid var(--swag-line);
    }

    .left-page {
        padding-right: 4px;
    }

    .right-page {
        padding-right: 0;
        padding-left: 0;
    }
}

@media (max-width: 480px) {
    :root {
        --swag-header-height: 146px;
    }

    .site-nav {
        display: block;
    }

    .site-brand {
        display: inline-block;
        margin-bottom: 10px;
    }

    .site-links {
        justify-content: flex-start;
    }

    .blockquote {
        margin-right: 0;
        margin-left: 0;
    }

    .container table {
        display: block;
        overflow-x: auto;
    }
}
)";
        return result;
    }

    Utf8 constructPage(const PageOptions& options, const std::string_view toc, const std::string_view content, const bool pages)
    {
        Utf8 result = std::format("<!DOCTYPE html>\n<html lang=\"en\" style=\"--swag-code-default: #{:06x}\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n", options.syntaxDefaultColor & 0x00FFFFFF);
        if (!options.titleContent.empty())
            result.append(std::format("<title>{}</title>\n", escapeHtml(options.titleContent)));
        if (!options.icon.empty())
            result.append(std::format("<link rel=\"icon\" type=\"image/x-icon\" href=\"{}\">\n", escapeHtml(options.icon, true)));
        if (!options.css.empty())
            result.append(std::format("<link rel=\"stylesheet\" type=\"text/css\" href=\"{}\">\n", escapeHtml(options.css, true)));
        result += "</head>\n<body>\n";
        result += R"(<header class="site-header">
<nav class="site-nav" aria-label="Main navigation">
<a class="site-brand" href="index.html">SWAG</a>
<div class="site-links">
<a href="index.html">Home</a>
<a href="language.html">Documentation</a>
<a href="swag.runtime.html">Runtime</a>
<a href="std.html">Std</a>
<a href="https://www.youtube.com/channel/UC9dkBu1nNfJDxUML7r7QH1Q">YouTube</a>
<a href="https://github.com/swag-lang/swc">GitHub</a>
</div>
</nav>
</header>
)";
        result += pages ? "<main class=\"container single-page\">\n" : "<main class=\"container\">\n";
        if (!pages)
        {
            result += "<aside class=\"left\"><div class=\"left-page\">\n";
            result.append(toc);
            result += "</div></aside>\n";
        }
        result += "<section class=\"right\"><article class=\"right-page\">\n";
        result.append(content);
        if (options.hasSwagWatermark)
            result.append(std::format("<div class=\"swag-watermark\">Generated with <a href=\"https://github.com/swag-lang/swc\">swc</a> {}.{}.{}</div>\n", SWC_VERSION, SWC_REVISION, SWC_BUILD_NUM));
        result += "</article></section>\n</main>\n";
        result += "</body>\n</html>\n";
        return result;
    }
}

SWC_END_NAMESPACE();
