// ReSharper disable CppClangTidyModernizeUseDesignatedInitializers
#pragma once
#include "Lexer/KeyTable.h"

enum class SubTokenIdentifierId : uint16_t
{
    Invalid = 0,
    
    // Control flow
    If,
    Else,
    Elif,
    For,
    While,
    Switch,
    Defer,
    Foreach,
    Where,
    Verify,
    Break,
    Fallthrough,
    Unreachable,
    Return,
    Case,
    Continue,
    Default,

    // Logical operators
    And,
    Or,
    OrElse,

    // Range/iteration
    To,
    Until,
    In,
    As,
    Is,
    Do,

    // Module/error handling
    Using,
    With,
    Cast,
    DRef,
    RetVal,
    Try,
    TryCatch,
    Catch,
    Assume,
    Throw,
    Discard,

    // Literals
    True,
    False,
    Null,
    Undefined,

    // Access modifiers
    Public,
    Internal,
    Private,

    // Type definitions
    Enum,
    Struct,
    Union,
    Impl,
    Interface,
    Func,
    Mtd,
    Namespace,
    Alias,
    Attr,
    Var,
    Let,
    Const,
    MoveRef,

    // Reserved
    Not,

    // Compiler directives
    CompilerGlobal,
    CompilerRun,
    CompilerAst,
    CompilerFuncTest,
    CompilerFuncInit,
    CompilerFuncDrop,
    CompilerFuncMain,
    CompilerFuncPreMain,
    CompilerFuncMessage,
    CompilerDependencies,
    CompilerInclude,
    CompilerLoad,
    CompilerAssert,
    CompilerPrint,
    CompilerError,
    CompilerWarning,
    CompilerForeignLib,
    CompilerImport,
    CompilerInject,
    CompilerMacro,
    CompilerIf,
    CompilerElse,
    CompilerElseIf,
    CompilerCode,
    CompilerScope,
    CompilerUp,
    CompilerType,

    // Modifiers
    ModifierPromote,
    ModifierWrap,
    ModifierNoDrop,
    ModifierMove,
    ModifierMoveRaw,
    ModifierReverse,
    ModifierRef,
    ModifierConstRef,
    ModifierNullable,
    ModifierErr,
    ModifierNoErr,
    ModifierBit,
    ModifierUnConst,

    // Compiler info
    CompilerBuildCfg,
    CompilerOs,
    CompilerArch,
    CompilerCpu,
    CompilerBackend,
    CompilerModule,
    CompilerFile,
    CompilerLine,
    CompilerScopeName,
    CompilerCurLocation,
    CompilerCallerLocation,
    CompilerCallerFunction,
    CompilerBuildVersion,
    CompilerBuildRevision,
    CompilerBuildNum,
    CompilerSwagOs,

    // Compiler introspection
    CompilerDefined,
    CompilerOffsetOf,
    CompilerAlignOf,
    CompilerSizeOf,
    CompilerTypeOf,
    CompilerStringOf,
    CompilerNameOf,
    CompilerIsConstExpr,
    CompilerLocation,
    CompilerDeclType,
    CompilerHasTag,
    CompilerGetTag,
    CompilerRunes,
    CompilerSafety,

    // Intrinsics - string/type
    IntrinsicStringCmp,
    IntrinsicTypeCmp,
    IntrinsicIs,
    IntrinsicAs,
    IntrinsicGetContext,
    IntrinsicSetContext,
    IntrinsicCompiler,
    IntrinsicPrint,
    IntrinsicCompilerError,
    IntrinsicCompilerWarning,
    IntrinsicBcBreakpoint,
    IntrinsicAssert,
    IntrinsicPanic,

    // Intrinsics - lifecycle
    IntrinsicInit,
    IntrinsicDrop,
    IntrinsicPostMove,
    IntrinsicPostCopy,

    // Intrinsics - type info
    IntrinsicKindOf,
    IntrinsicCountOf,
    IntrinsicDataOf,

    // Intrinsics - constructors
    IntrinsicMakeSlice,
    IntrinsicMakeString,
    IntrinsicMakeAny,
    IntrinsicMakeInterface,
    IntrinsicMakeCallback,
    IntrinsicTableOf,
    IntrinsicDbgAlloc,
    IntrinsicSysAlloc,

    // Intrinsics - runtime
    IntrinsicGetErr,
    IntrinsicArguments,
    IntrinsicIsByteCode,
    IntrinsicIndex,
    IntrinsicRtFlags,
    IntrinsicGetProcessInfos,
    IntrinsicModules,
    IntrinsicGvtd,

    // Intrinsics - bit operations
    IntrinsicByteSwap,
    IntrinsicBitCountNz,
    IntrinsicBitCountTz,
    IntrinsicBitCountLz,
    IntrinsicRol,
    IntrinsicRor,

    // Intrinsics - math
    IntrinsicMin,
    IntrinsicMax,
    IntrinsicSqrt,
    IntrinsicSin,
    IntrinsicCos,
    IntrinsicTan,
    IntrinsicSinh,
    IntrinsicCosh,
    IntrinsicTanh,
    IntrinsicASin,
    IntrinsicACos,
    IntrinsicATan,
    IntrinsicATan2,
    IntrinsicLog,
    IntrinsicLog2,
    IntrinsicLog10,
    IntrinsicFloor,
    IntrinsicCeil,
    IntrinsicTrunc,
    IntrinsicRound,
    IntrinsicAbs,
    IntrinsicExp,
    IntrinsicExp2,
    IntrinsicPow,

    // Intrinsics - memory
    IntrinsicAlloc,
    IntrinsicRealloc,
    IntrinsicFree,
    IntrinsicMemCpy,
    IntrinsicMemMove,
    IntrinsicMemSet,
    IntrinsicMemCmp,
    IntrinsicMulAdd,
    IntrinsicStrLen,
    IntrinsicStrCmp,

    // Intrinsics - atomic
    IntrinsicAtomicAdd,
    IntrinsicAtomicAnd,
    IntrinsicAtomicOr,
    IntrinsicAtomicXor,
    IntrinsicAtomicXchg,
    IntrinsicAtomicCmpXchg,

    // Intrinsics - varargs
    IntrinsicCVaStart,
    IntrinsicCVaEnd,
    IntrinsicCVaArg,

    // CVarArgs keyword
    CVarArgs,

    // Native types
    Any,
    Void,
    Rune,
    F32,
    F64,
    S8,
    S16,
    S32,
    S64,
    U8,
    U16,
    U32,
    U64,
    Bool,
    String,
    CString,
    TypeInfo,
};

using KeywordFlags = Flags<uint32_t>;

constexpr std::array<KwPair, 249> K_KEYWORDS = {{
    // Control flow
    {"if", SubTokenIdentifierId::If, 0},
    {"else", SubTokenIdentifierId::Else, 0},
    {"elif", SubTokenIdentifierId::Elif, 0},
    {"for", SubTokenIdentifierId::For, 0},
    {"while", SubTokenIdentifierId::While, 0},
    {"switch", SubTokenIdentifierId::Switch, 0},
    {"defer", SubTokenIdentifierId::Defer, 0},
    {"foreach", SubTokenIdentifierId::Foreach, 0},
    {"where", SubTokenIdentifierId::Where, 0},
    {"verify", SubTokenIdentifierId::Verify, 0},
    {"break", SubTokenIdentifierId::Break, 0},
    {"fallthrough", SubTokenIdentifierId::Fallthrough, 0},
    {"unreachable", SubTokenIdentifierId::Unreachable, 0},
    {"return", SubTokenIdentifierId::Return, 0},
    {"case", SubTokenIdentifierId::Case, 0},
    {"continue", SubTokenIdentifierId::Continue, 0},
    {"default", SubTokenIdentifierId::Default, 0},

    // Logical operators
    {"and", SubTokenIdentifierId::And, 0},
    {"or", SubTokenIdentifierId::Or, 0},
    {"orelse", SubTokenIdentifierId::OrElse, 0},

    // Range/iteration
    {"to", SubTokenIdentifierId::To, 0},
    {"until", SubTokenIdentifierId::Until, 0},
    {"in", SubTokenIdentifierId::In, 0},
    {"as", SubTokenIdentifierId::As, 0},
    {"is", SubTokenIdentifierId::Is, 0},
    {"do", SubTokenIdentifierId::Do, 0},

    // Module/error handling
    {"using", SubTokenIdentifierId::Using, 0},
    {"with", SubTokenIdentifierId::With, 0},
    {"cast", SubTokenIdentifierId::Cast, 0},
    {"dref", SubTokenIdentifierId::DRef, 0},
    {"retval", SubTokenIdentifierId::RetVal, 0},
    {"try", SubTokenIdentifierId::Try, 0},
    {"trycatch", SubTokenIdentifierId::TryCatch, 0},
    {"catch", SubTokenIdentifierId::Catch, 0},
    {"assume", SubTokenIdentifierId::Assume, 0},
    {"throw", SubTokenIdentifierId::Throw, 0},
    {"discard", SubTokenIdentifierId::Discard, 0},

    // Literals
    {"true", SubTokenIdentifierId::True, 0},
    {"false", SubTokenIdentifierId::False, 0},
    {"null", SubTokenIdentifierId::Null, 0},
    {"undefined", SubTokenIdentifierId::Undefined, 0},

    // Access modifiers
    {"public", SubTokenIdentifierId::Public, 0},
    {"internal", SubTokenIdentifierId::Internal, 0},
    {"private", SubTokenIdentifierId::Private, 0},

    // Type definitions
    {"enum", SubTokenIdentifierId::Enum, 0},
    {"struct", SubTokenIdentifierId::Struct, 0},
    {"union", SubTokenIdentifierId::Union, 0},
    {"impl", SubTokenIdentifierId::Impl, 0},
    {"interface", SubTokenIdentifierId::Interface, 0},
    {"func", SubTokenIdentifierId::Func, 0},
    {"mtd", SubTokenIdentifierId::Mtd, 0},
    {"namespace", SubTokenIdentifierId::Namespace, 0},
    {"alias", SubTokenIdentifierId::Alias, 0},
    {"attr", SubTokenIdentifierId::Attr, 0},
    {"var", SubTokenIdentifierId::Var, 0},
    {"let", SubTokenIdentifierId::Let, 0},
    {"const", SubTokenIdentifierId::Const, 0},
    {"moveref", SubTokenIdentifierId::MoveRef, 0},

    // Reserved
    {"not", SubTokenIdentifierId::Not, 0},

    // Compiler directives
    {"#global", SubTokenIdentifierId::CompilerGlobal, 0},
    {"#run", SubTokenIdentifierId::CompilerRun, 0},
    {"#ast", SubTokenIdentifierId::CompilerAst, 0},
    {"#test", SubTokenIdentifierId::CompilerFuncTest, 0},
    {"#init", SubTokenIdentifierId::CompilerFuncInit, 0},
    {"#drop", SubTokenIdentifierId::CompilerFuncDrop, 0},
    {"#main", SubTokenIdentifierId::CompilerFuncMain, 0},
    {"#premain", SubTokenIdentifierId::CompilerFuncPreMain, 0},
    {"#message", SubTokenIdentifierId::CompilerFuncMessage, 0},
    {"#dependencies", SubTokenIdentifierId::CompilerDependencies, 0},
    {"#include", SubTokenIdentifierId::CompilerInclude, 0},
    {"#load", SubTokenIdentifierId::CompilerLoad, 0},
    {"#assert", SubTokenIdentifierId::CompilerAssert, 0},
    {"#print", SubTokenIdentifierId::CompilerPrint, 0},
    {"#error", SubTokenIdentifierId::CompilerError, 0},
    {"#warning", SubTokenIdentifierId::CompilerWarning, 0},
    {"#foreignlib", SubTokenIdentifierId::CompilerForeignLib, 0},
    {"#import", SubTokenIdentifierId::CompilerImport, 0},
    {"#inject", SubTokenIdentifierId::CompilerInject, 0},
    {"#macro", SubTokenIdentifierId::CompilerMacro, 0},
    {"#if", SubTokenIdentifierId::CompilerIf, 0},
    {"#else", SubTokenIdentifierId::CompilerElse, 0},
    {"#elif", SubTokenIdentifierId::CompilerElseIf, 0},
    {"#code", SubTokenIdentifierId::CompilerCode, 0},
    {"#scope", SubTokenIdentifierId::CompilerScope, 0},
    {"#up", SubTokenIdentifierId::CompilerUp, 0},
    {"#type", SubTokenIdentifierId::CompilerType, 0},

    // Modifiers
    {"#prom", SubTokenIdentifierId::ModifierPromote, 0},
    {"#wrap", SubTokenIdentifierId::ModifierWrap, 0},
    {"#nodrop", SubTokenIdentifierId::ModifierNoDrop, 0},
    {"#move", SubTokenIdentifierId::ModifierMove, 0},
    {"#moveraw", SubTokenIdentifierId::ModifierMoveRaw, 0},
    {"#reverse", SubTokenIdentifierId::ModifierReverse, 0},
    {"#ref", SubTokenIdentifierId::ModifierRef, 0},
    {"#constref", SubTokenIdentifierId::ModifierConstRef, 0},
    {"#null", SubTokenIdentifierId::ModifierNullable, 0},
    {"#err", SubTokenIdentifierId::ModifierErr, 0},
    {"#noerr", SubTokenIdentifierId::ModifierNoErr, 0},
    {"#bit", SubTokenIdentifierId::ModifierBit, 0},
    {"#unconst", SubTokenIdentifierId::ModifierUnConst, 0},

    // Compiler info
    {"#cfg", SubTokenIdentifierId::CompilerBuildCfg, 0},
    {"#os", SubTokenIdentifierId::CompilerOs, 0},
    {"#arch", SubTokenIdentifierId::CompilerArch, 0},
    {"#cpu", SubTokenIdentifierId::CompilerCpu, 0},
    {"#backend", SubTokenIdentifierId::CompilerBackend, 0},
    {"#module", SubTokenIdentifierId::CompilerModule, 0},
    {"#file", SubTokenIdentifierId::CompilerFile, 0},
    {"#line", SubTokenIdentifierId::CompilerLine, 0},
    {"#scopename", SubTokenIdentifierId::CompilerScopeName, 0},
    {"#curlocation", SubTokenIdentifierId::CompilerCurLocation, 0},
    {"#callerlocation", SubTokenIdentifierId::CompilerCallerLocation, 0},
    {"#callerfunction", SubTokenIdentifierId::CompilerCallerFunction, 0},
    {"#swagversion", SubTokenIdentifierId::CompilerBuildVersion, 0},
    {"#swagrevision", SubTokenIdentifierId::CompilerBuildRevision, 0},
    {"#swagbuildnum", SubTokenIdentifierId::CompilerBuildNum, 0},
    {"#swagos", SubTokenIdentifierId::CompilerSwagOs, 0},

    // Compiler introspection
    {"#defined", SubTokenIdentifierId::CompilerDefined, 0},
    {"#offsetof", SubTokenIdentifierId::CompilerOffsetOf, 0},
    {"#alignof", SubTokenIdentifierId::CompilerAlignOf, 0},
    {"#sizeof", SubTokenIdentifierId::CompilerSizeOf, 0},
    {"#typeof", SubTokenIdentifierId::CompilerTypeOf, 0},
    {"#stringof", SubTokenIdentifierId::CompilerStringOf, 0},
    {"#nameof", SubTokenIdentifierId::CompilerNameOf, 0},
    {"#isconstexpr", SubTokenIdentifierId::CompilerIsConstExpr, 0},
    {"#location", SubTokenIdentifierId::CompilerLocation, 0},
    {"#decltype", SubTokenIdentifierId::CompilerDeclType, 0},
    {"#hastag", SubTokenIdentifierId::CompilerHasTag, 0},
    {"#gettag", SubTokenIdentifierId::CompilerGetTag, 0},
    {"#runes", SubTokenIdentifierId::CompilerRunes, 0},
    {"#safety", SubTokenIdentifierId::CompilerSafety, 0},

    // Intrinsics - string/type
    {"@stringcmp", SubTokenIdentifierId::IntrinsicStringCmp, 0},
    {"@typecmp", SubTokenIdentifierId::IntrinsicTypeCmp, 0},
    {"@is", SubTokenIdentifierId::IntrinsicIs, 0},
    {"@as", SubTokenIdentifierId::IntrinsicAs, 0},
    {"@getcontext", SubTokenIdentifierId::IntrinsicGetContext, 0},
    {"@setcontext", SubTokenIdentifierId::IntrinsicSetContext, 0},
    {"@compiler", SubTokenIdentifierId::IntrinsicCompiler, 0},
    {"@print", SubTokenIdentifierId::IntrinsicPrint, 0},
    {"@compilererror", SubTokenIdentifierId::IntrinsicCompilerError, 0},
    {"@compilerwarning", SubTokenIdentifierId::IntrinsicCompilerWarning, 0},
    {"@breakpoint", SubTokenIdentifierId::IntrinsicBcBreakpoint, 0},
    {"@assert", SubTokenIdentifierId::IntrinsicAssert, 0},
    {"@panic", SubTokenIdentifierId::IntrinsicPanic, 0},

    // Intrinsics - lifecycle
    {"@init", SubTokenIdentifierId::IntrinsicInit, 0},
    {"@drop", SubTokenIdentifierId::IntrinsicDrop, 0},
    {"@postmove", SubTokenIdentifierId::IntrinsicPostMove, 0},
    {"@postcopy", SubTokenIdentifierId::IntrinsicPostCopy, 0},

    // Intrinsics - type info
    {"@kindof", SubTokenIdentifierId::IntrinsicKindOf, 0},
    {"@countof", SubTokenIdentifierId::IntrinsicCountOf, 0},
    {"@dataof", SubTokenIdentifierId::IntrinsicDataOf, 0},

    // Intrinsics - constructors
    {"@mkslice", SubTokenIdentifierId::IntrinsicMakeSlice, 0},
    {"@mkstring", SubTokenIdentifierId::IntrinsicMakeString, 0},
    {"@mkany", SubTokenIdentifierId::IntrinsicMakeAny, 0},
    {"@mkinterface", SubTokenIdentifierId::IntrinsicMakeInterface, 0},
    {"@mkcallback", SubTokenIdentifierId::IntrinsicMakeCallback, 0},
    {"@tableof", SubTokenIdentifierId::IntrinsicTableOf, 0},
    {"@dbgalloc", SubTokenIdentifierId::IntrinsicDbgAlloc, 0},
    {"@sysalloc", SubTokenIdentifierId::IntrinsicSysAlloc, 0},

    // Intrinsics - runtime
    {"@err", SubTokenIdentifierId::IntrinsicGetErr, 0},
    {"@args", SubTokenIdentifierId::IntrinsicArguments, 0},
    {"@bytecode", SubTokenIdentifierId::IntrinsicIsByteCode, 0},
    {"@index", SubTokenIdentifierId::IntrinsicIndex, 0},
    {"@rtflags", SubTokenIdentifierId::IntrinsicRtFlags, 0},
    {"@pinfos", SubTokenIdentifierId::IntrinsicGetProcessInfos, 0},
    {"@modules", SubTokenIdentifierId::IntrinsicModules, 0},
    {"@gvtd", SubTokenIdentifierId::IntrinsicGvtd, 0},

    // Intrinsics - bit operations
    {"@byteswap", SubTokenIdentifierId::IntrinsicByteSwap, 0},
    {"@bitcountnz", SubTokenIdentifierId::IntrinsicBitCountNz, 0},
    {"@bitcounttz", SubTokenIdentifierId::IntrinsicBitCountTz, 0},
    {"@bitcountlz", SubTokenIdentifierId::IntrinsicBitCountLz, 0},
    {"@rol", SubTokenIdentifierId::IntrinsicRol, 0},
    {"@ror", SubTokenIdentifierId::IntrinsicRor, 0},

    // Intrinsics - math
    {"@min", SubTokenIdentifierId::IntrinsicMin, 0},
    {"@max", SubTokenIdentifierId::IntrinsicMax, 0},
    {"@sqrt", SubTokenIdentifierId::IntrinsicSqrt, 0},
    {"@sin", SubTokenIdentifierId::IntrinsicSin, 0},
    {"@cos", SubTokenIdentifierId::IntrinsicCos, 0},
    {"@tan", SubTokenIdentifierId::IntrinsicTan, 0},
    {"@sinh", SubTokenIdentifierId::IntrinsicSinh, 0},
    {"@cosh", SubTokenIdentifierId::IntrinsicCosh, 0},
    {"@tanh", SubTokenIdentifierId::IntrinsicTanh, 0},
    {"@asin", SubTokenIdentifierId::IntrinsicASin, 0},
    {"@acos", SubTokenIdentifierId::IntrinsicACos, 0},
    {"@atan", SubTokenIdentifierId::IntrinsicATan, 0},
    {"@atan2", SubTokenIdentifierId::IntrinsicATan2, 0},
    {"@log", SubTokenIdentifierId::IntrinsicLog, 0},
    {"@log2", SubTokenIdentifierId::IntrinsicLog2, 0},
    {"@log10", SubTokenIdentifierId::IntrinsicLog10, 0},
    {"@floor", SubTokenIdentifierId::IntrinsicFloor, 0},
    {"@ceil", SubTokenIdentifierId::IntrinsicCeil, 0},
    {"@trunc", SubTokenIdentifierId::IntrinsicTrunc, 0},
    {"@round", SubTokenIdentifierId::IntrinsicRound, 0},
    {"@abs", SubTokenIdentifierId::IntrinsicAbs, 0},
    {"@exp", SubTokenIdentifierId::IntrinsicExp, 0},
    {"@exp2", SubTokenIdentifierId::IntrinsicExp2, 0},
    {"@pow", SubTokenIdentifierId::IntrinsicPow, 0},

    // Intrinsics - memory
    {"@alloc", SubTokenIdentifierId::IntrinsicAlloc, 0},
    {"@realloc", SubTokenIdentifierId::IntrinsicRealloc, 0},
    {"@free", SubTokenIdentifierId::IntrinsicFree, 0},
    {"@memcpy", SubTokenIdentifierId::IntrinsicMemCpy, 0},
    {"@memmove", SubTokenIdentifierId::IntrinsicMemMove, 0},
    {"@memset", SubTokenIdentifierId::IntrinsicMemSet, 0},
    {"@memcmp", SubTokenIdentifierId::IntrinsicMemCmp, 0},
    {"@muladd", SubTokenIdentifierId::IntrinsicMulAdd, 0},
    {"@strlen", SubTokenIdentifierId::IntrinsicStrLen, 0},
    {"@strcmp", SubTokenIdentifierId::IntrinsicStrCmp, 0},

    // Intrinsics - atomic
    {"@atomadd", SubTokenIdentifierId::IntrinsicAtomicAdd, 0},
    {"@atomand", SubTokenIdentifierId::IntrinsicAtomicAnd, 0},
    {"@atomor", SubTokenIdentifierId::IntrinsicAtomicOr, 0},
    {"@atomxor", SubTokenIdentifierId::IntrinsicAtomicXor, 0},
    {"@atomxchg", SubTokenIdentifierId::IntrinsicAtomicXchg, 0},
    {"@atomcmpxchg", SubTokenIdentifierId::IntrinsicAtomicCmpXchg, 0},

    // Intrinsics - varargs
    {"@cvastart", SubTokenIdentifierId::IntrinsicCVaStart, 0},
    {"@cvaend", SubTokenIdentifierId::IntrinsicCVaEnd, 0},
    {"@cvaarg", SubTokenIdentifierId::IntrinsicCVaArg, 0},

    // CVarArgs keyword
    {"cvarargs", SubTokenIdentifierId::CVarArgs, 0},

    // Native types
    {"any", SubTokenIdentifierId::Any, 0},
    {"void", SubTokenIdentifierId::Void, 0},
    {"rune", SubTokenIdentifierId::Rune, 0},
    {"f32", SubTokenIdentifierId::F32, 0},
    {"f64", SubTokenIdentifierId::F64, 0},
    {"s8", SubTokenIdentifierId::S8, 0},
    {"s16", SubTokenIdentifierId::S16, 0},
    {"s32", SubTokenIdentifierId::S32, 0},
    {"s64", SubTokenIdentifierId::S64, 0},
    {"u8", SubTokenIdentifierId::U8, 0},
    {"u16", SubTokenIdentifierId::U16, 0},
    {"u32", SubTokenIdentifierId::U32, 0},
    {"u64", SubTokenIdentifierId::U64, 0},
    {"bool", SubTokenIdentifierId::Bool, 0},
    {"string", SubTokenIdentifierId::String, 0},
    {"cstring", SubTokenIdentifierId::CString, 0},
    {"typeinfo", SubTokenIdentifierId::TypeInfo, 0},
}};

constexpr KwTable<1024> KEYWORD_TABLE{K_KEYWORDS};
